### ISSUE TITLE
Request for Arabic Support

### ISSUE THREAD

**Issue by haythamfouda** [gershnik/Translit#1] opened 2024-12-09 13:18 UTC
Seems like a great product you're offering here. I was wondering if there are any plans to add Arabic support. For reference check [Yamli](https://www.yamli.com/ar/). This is pretty much what I'm looking for but with system-wide support like what your product offers. Thanks!

**Comment by gershnik** [comment] 2024-12-09 16:29
This is certainly possible but the problem is that my own knowledge of Arabic is limited to a few letters (once upon a time I set to learn to at least read it but other things interfered). Looking at the Yamli help at https://www.yamli.com/help/ a few things jump out at me. 
- They don't seem to provide the actual transliteration table e.g. m - م etc. Is it available somewhere?
- More interestingly they provide you a choice of words when the input is ambiguous. Ambiguity is not an issue with Hebrew transliteration scheme and seldom with Russian (and in a few cases when it is, the workaround is easy) so Translit currently doesn't have support for such functionality. It is possible to add it as the Apple frameworks support such use case but it will turn the whole thing into a much larger project. Ditto for support of dashes or merging words (e.g. how it handles "al" prefix - the equivalent Hebrew "h" must currently be typed with the word that follows). 

Generally it appears that Yamli is much more than a simple transliteration - it is more like a "phonetic input" engine. 

So how important are all these phonetic input features? If they are a "must have" for a reasonable typing experience in Arabic then this will probably not be something I could undertake at this time. 

If it is possible to just get around with a more simple transliteration scheme where you have 1-1 correspondence between some English letters and Arabic then this is certainly doable. To attempt it I'll need:
- The transliteration scheme
- Someone to ask questions of
- A beta tester 🙂

Let me know your thoughts.

**Comment by haythamfouda** [comment] 2024-12-09 19:31
Thanks for your reply. Well, unfortunately it's not gonna be a simple 1-1 mapping between Arabic and English letters. It's gonna be much more complicated than that. Anyways if you ever feel like digging into it, I'm willing to answer any questions or test your Arabic version.

**Comment by gershnik** [comment] 2024-12-09 23:57
I think "1-1" was a poor word choice on my part. What I meant to say is "without ambiguities" rather than 1 English letter for 1 Arabic (letter combinations are fine). 

Looking at https://en.wikipedia.org/wiki/Arabic_chat_alphabet and other examples I found online it is indeed complicated. There seems to be no generally accepted way of transliteration and lots of letters have identical ones. However, it does seem to be possible to pick one of them.

How useful/usable would for example be something like this:

| Latin | Arabic
|-------|-------
| a  | ا‎ | 
| b  | ب‎ | 
| c  |   |
| d  | د‎ | 
| dh | ذ‎ | 
| D  | ض‎ | 
| e  |   |
| f  | ف‎ | 
| g  | غ‎ | 
| h  | ه‎ | 
| H  | ح‎ | 
| i  | ي‎ |
| j  | ج‎ | 
| k  | ك‎ | 
| kh | خ‎ | 
| l  | ل‎ |
| m  | م‎ | 
| n  | ن‎ | 
| o  | ء |
| p  |   |
| q  | ق‎ | 
| r  | ر‎ |
| s  | س‎ | 
| sh | ش‎ | 
| S  | ص‎ | 
| t  | ت‎ | 
| th | ث‎ | 
| T  | ط‎ | 
| u  |   |
| v  |   |
| w  | و‎ | 
| x  |   |   
| y  | ع‎ | 
| z  | ز‎ | 
| Z  | ظ‎ | 

Note that this leaves quite a few Latin letters unassigned which could be used as duplicates for others or for some other purpose

**Comment by gershnik** [comment] 2024-12-10 01:00
I think "1-1" was a poor word choice on my part. What I meant to say is "without ambiguities" rather than 1 English letter for 1 Arabic (letter combinations are fine). 

Looking at https://en.wikipedia.org/wiki/Arabic_chat_alphabet and other examples I found online it is indeed complicated. There seems to be no generally accepted way of transliteration and lots of letters have identical ones. However, it does seem to be possible to pick one of them.

How useful/usable would for example be something like this:

| Latin | Arabic
|-------|-------
| a  | ا‎ |
| b  | ب‎ |
| c  |   |
| d  | د‎ |
| dh | ذ‎ |
| D  | ض‎ |
| e  |   |
| f  | ف‎ |
| g  | غ‎ |
| h  | ه‎ |
| H  | ح‎ |
| i  | ي‎ |
| j  | ج‎ |
| k  | ك‎ |
| kh | خ‎ |
| l  | ل‎ |
| m  | م‎ |
| n  | ن‎ |
| o  | ء |
| p  |   |
| q  | ق‎ |
| r  | ر‎ |
| s  | س‎ |
| sh | ش‎ |
| S  | ص‎ |
| t  | ت‎ |
| th | ث‎ |
| T  | ط‎ |
| u  |   |
| v  |   |
| w  | و‎ |
| x  |   | 
| y  | ع‎ |
| z  | ز‎ |
| Z  | ظ‎ |

Note that quite a few Latin letters are left unassigned and could be used as either duplicates (e.g. p/f) or other purposes. 
It is definitely not as sleek as Yamli but way simpler to implement 🙂

**Comment by gershnik** [comment] 2024-12-31 05:37
Out of scope for the current implementation

**Closed as not planned by gershnik** 2024-12-31 05:37 UTC
